#!/bin/bash

set -Eeo pipefail

stack_env=dev
stack_name=data-pipeline
tf_dir=terraform

function tf_init {
    directory=$1
    terraform init -backend-config key=${stack_env}/${stack_name}/terraform.tfstate ${directory}
}

for command in "$@"
do
    echo "--- ${command} ---"
    case "${command}" in
        validate)
            tf_init ${tf_dir}
            terraform validate ${tf_dir}
        ;;
        dojo-validate)
            dojo "./tasks validate"
        ;;
        plan)
            tf_init ${tf_dir}
            terraform plan -var environment=${stack_env} -out=dev.tfplan ${tf_dir}
        ;;
        dojo-plan)
            dojo "./tasks plan"
        ;;
        apply)
            tf_init ${tf_dir}
            terraform apply dev.tfplan
        ;;
        dojo-apply)
            dojo "./tasks apply"
        ;;
        *)
            echo "Invalid command: '${command}'"
            exit 1
        ;;
    esac
done

set +e
