format_version: 4
pipelines:
  "data-pipeline-ecs-cluster":
    group: gp2gp-data-pipeline-infra
    label_template: "${git[:8]}"
    materials:
      mydependency:
        pipeline: data-pipeline-container-repositories
        stage: apply_dev
        ignore_for_scheduling: false
      git:
        type: configrepo
        includes:
          - stacks/ecs-cluster/**/*
    stages:
      - validate:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-validate ecs-cluster dev
      - plan_dev:
          clean_workspace: true
          jobs:
            plan:
              resources:
                - docker
              artifacts:
                - build:
                    source: dev.tfplan
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dojo-plan ecs-cluster dev